### ISSUE TITLE
Не могу понять что не так....

### ISSUE THREAD

**Issue by ShakunBoris** [Mmm-Vvv/Romeo_plugins#2]
JAA PLUGIN ERROR: plugin_mmm_radio error on load: Cannot find mpv-1.dll or mpv-2.dll in your system %PATH%. One way to deal with this is to ship the dll with your script and put the directory your script is in into %PATH% before "import mpv": os.environ["PATH"] = os.path.dirname(__file__) + os.pathsep + os.environ["PATH"] If mpv-1.dll is located elsewhere, you can add that path to os.environ["PATH"].

**Comment by Mmm-Vvv** [comment]
Для работы требуется mpv:
pip install mpv

**Comment by ShakunBoris** [comment]
а так же  mpv-1.dll, он в комплекте не идет, как я понял, с библиотекой, отдельно выкачивать пришлось.

**Comment by Mmm-Vvv** [comment]
Ставил на линуксе (RaspbianOS). Ничего докачивать не пришлось.
dll - это скорее всего под Windows, так что не подскажу
