### ISSUE TITLE
core.context_clear_play(), core.accept() таких нет

### ISSUE THREAD

**Issue by ShakunBoris** [Mmm-Vvv/Romeo_plugins#3]
core.context_clear_play(), core.accept() 
таких не знает. без вот этого работает, можно просто закомментить core.accept(). со вторым лень разбираться.

**Comment by Mmm-Vvv** [comment]
Это я допиливал vacore.py под себя. Сейчас закомментирую их в плагине

**Comment by Mmm-Vvv** [comment]
Готово, убрал
